var GAME_LEVELS = [
 

 {
  name: 'pnumonic device',
  difficulty: 8,
  coins: 18,
  powerups: ['haste', 'lowjump', 'doublejump'],
  layout:  ["                                   xx                                                                                                    !                                                                                    xx",
            "                                   xx                                                                                                    !                                                                                    xx",
            "                                   xx                                                                                                  !!!!!   *  o o o o                                                                     xx",
            "                                   xx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    !!!   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                v          v xx",
            "                                   xx        xx                                                                                   xx     !                 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                      v  v   xx",
            "                                   xx       xx       |                         |               |                                  xx        v                  v   v      v    v       v      v     v   v     v       v    v  xx",
            "            @                      xx      xx                  |       |                                      |                   xx     ! v    v                                                v            v               xx",
            "                                   xxxx             |                                 |               |                           xx     !             v          v       v         v   v   v                       v    v   vxx",
            "       !!!!! !!!!!                 xx                                                                                             xx   !!!!!  v                               v                           v                   xx",
            "       xxxxx xxxxx                 xx o o     xxxxxx  |xxxxxx | xxxxx|  xxxxx | xxxxx|  xxxxx | xxxxx|  xxxxx                     xx    !!!  v          v      v          v            v      v    v           v     v    v  vxx",
            "       !!!!! !!!!!                 xx         !!!!!!   !!!!!!   !!!!!   !!!!!   !!!!!   !!!!!   !!!!!   !!!!!|  !x                xx     !     v                         v                           v      v    v   v        xx",
            "       !!!!! !!!!!                 xxxxxxxxxxx!    !   !    !|  !   ! | !   !   !   !   !   !   !   ! | !   !   !xxx              xx                   v           v      v     v  v                      v            v      xx",
            "       vvvvv vvvvv                 xxxxxxxxxxx!    ! o !    ! o !   ! o !   !|o !   ! o|!   !|o !   ! o !   ! o|!x                xx     !    v   v                        v                     v    v        v       v    v xx",
            " o                                 xx!!!!!!!!!!    !!!!!    !!!!!   !!!!!   !!!!!   !!!!!   !!!!!   !!!!!   !!!!!x                xx     !         v                          v      v     v                       v      v   xx",
            "                                   xxv                                                                                            xx   !!!!!                       v                                              v   v       xx",
            "xx                                 xx                                                                                 xxxxxxx     xx    !!!                   v                     v               v       v        v      v xx",
            "xx                                 xx                                                                                 xxxxxxx     xx     !      v                               v                 v      v               v    xx",
            "xx                                 xx                                                                                             xx                                v     v        v                              v           xx",
            "xxxxxxxxxxxxxxxxxxxxxxx            xx o                                                                                           xx     !           v          v       v         v   v   v      v     v     v      v       v xx",
            "xxxxxxxxxxxxxxxxxxxxxxx            xx        xxxxxxx =  =  = xxxxxxx =  =  = xxxxxxx =  =  = xxxxxxx =  =  = xxxxxxx              xx     !             v          v       v         v   v   v                   v    v  v     xx",
            "xx!!!!!!!!!!!!!!!!!!!xx            xx        xxxxxxx=  = =  =xxxxxxx=  = =  =xxxxxxx=  = =  =xxxxxxx=  = =  =xxxxxxx              xx   !!!!!      v                v          v       v         v   v   v                   v xx",
            "xx!!!!!!!!!!!!!!!!!!!xx            xxxx                          v     v      v      v     v      v                               xx    !!!            v          v       v         v   v   v         v      v      v         xx",
            "xxxxxvvvvvvvvvvvvvvvvxx        =   xxxxx                                                                                          xx     !       v                v          v       v         v   v   v                 v    xx",
            "xx                   xx            xx!xxx                                                                                         xx                                                                   v   v     v            xx",
            "xx                   xx            xx!!xxx                                                                                        xx     !              v          v       v         v   v   v                       v        xx",
            "xx o o               xx            xx!!!xxx                                                                                       xx     !      v                v          v       v         v   v   v                      vxx",
            "xx                   xx            xx!!!!xxx                                                                                      xx   !!!!!                                                                                  xx",
            "xx                   xx =          xx!!!!!xxx                                                                                     xx    !!!                                                                                   xx",
            "xx                   xx            xx!!!!!!xxx                                                                                    xx     !                                                                                    xx",
            "xx                   xx            xx!!!!!!!xxx                                                             !     !               xx                                                                                          xx",
            "xxxxxxxx             xx            xx!!!!!!!!xxx                                                           !!!   !!!              xx     !                                                                        !           xx",
            "xxxxxxxx             xx       =    xxxxxxxxxxxxxxxxxxxx                                        !          !!!!! !!!!!             xx     !                                                                       !!!          xx",
            "xx                   xx            xxxxxxxxxxxxxxxxxxxx            !   !   !   !   !   !   !   !!        !!!!!!!!!!!!!            xx   !!!!!                                                                    !!!!!         xx",
            "xx                   xx                      xxx!!!!!xx             !   !   !   !   !   !   !  !!!       v!!!!!!!!!!!v            xx    !!!                                                                       !           xx",
            "xx          xxxx     xx                       xxx!!!!xxxx       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        !!!!!!!!!              xx     !                                                                        !           xx",
            "xx          xxxx     xx                        xxx!!!xx!!         !   !   !   !   !   !   !    !!!          !!!!!!!               xx                                                                              !       oo  xx",
            "xx                   xx                         xxx!!xx          !   !   !   !   !   !   !     !!            !!!!!                xx                                                                                          xx",
            "xx                   xx            xxxxxxxx      xxx!xx                                        !              !!!                 xx                                                                                          xx",
            "xxxxxxxxxx           xx            xxxxxxxxx      xxxxxxx                                                      !                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "xxxxxxxxxx           xx            xxxxxxxxxx      xxxx                                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "xx!!!!!!xxxxxxxx     xx     ooo    xxxxxxxxxxx      xxx                                                                                                                                                                       xx",
            "xx!!!!xxxxxxxxxx     xx     xxx    xxxxxxxxxxxx      xx                      xxxxxxxxxxxxxxxxx                                                                                                                                xx",
            "xx!!!xx            xxxx!!!!!!!!!!!!xxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                 xx",
            "xx!!xx             x!xxxx!!!!!!!!!xxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                =     =            =                  =           =                     xx",
            "xx!xx              x!xxxxx!!!!!!!xxxxxxxxxxxxxx                                                                       |              xxx                                                                                      xx",
            "xx!x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                             |                                               !!!                                      o        xx",
            "xxxx         xxxxxxxxxxxxxxxxxxxxxxxx                                                                    |                                                     !!!!!                                                          xx",
            "xx                                                                                                                       |    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xx",
            "xx                                                                                                             |                                                                                                              xx",
            "xxxxxxxxx                                                                                                             |                                                                                                       xx",
            "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvvvvvvvvvvvvvvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",                                                                                                                                                                                    
            "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  },         




  {
  name: 'beginner',
  rating: 1,
  coins: 2,
  powerups: [],
  layout:   ["                                                                                ",
             "     @                                                                          ",
             "                                                                                ",
             "                                                                                ",
             "                                                                                ",
             "                                                                                ",
             "                                                                  xxx           ",
             "                                                   xx      xx    xx!xx          ",
             "                                    o        xx                  x!!!x          ",
             "                                                                 xx!xx          ",
             "                                   xxxxx                          xvx           ",
             "                                                                            xx  ",
             "  xx                                                                         x  ",
             "  x                                                                          x  ",
             "  x                                      xxxxx                             o x  ",
             "  x          xxxx                                                            x  ",
             "  x          x  x                                                xxxxx       x  ",
             "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
             "                              x   x                  x     x                    ",
             "                              x!!!x                  x!!!!!x                    ",
             "                              x!!!x                  x!!!!!x                    ",
             "                              xxxxx                  xxxxxxx                    ",
             "                                                                                ",
             "                                                                                "],
  },          






  {
  name: 'Cape Cod',
  difficulty: 3,
  coins: 6,
  powerups: ['haste', 'lowjump', 'doublejump'],
  layout:   ["                                                              x!!!!!!!!!!!!!x                                     ",
             "                                                              x!!!!!!!!!!!!!x                                     ",
             "                                                              x!!!!!!!!!!!!!x                                     ",
             "                                      x!!x  o                 x!!!xxxxxxx!!!x                                x!x  ",
             "                                      x!!x                    xxxxx     xxxxx                                x!x  ",
             "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
             "                                      xx!!!!!!!!!!xxxx                      xx                               x!x  ",
             "                                       xxxxxxxxxx!!xxxxx                                                  o  x!x  ",
             "                                                xx!x   xxxxxxx     o                                        xx!x  ",
             "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
             "                                                 xvx         x     x   x                 !!!!!!!!!!!!!!!!!!!!!xx  ",
             "                                                             xx  |   |   |  xxxxxxx      !xxxxxxxxxxxxxxxxxxxxx   ",
             "                                                              xx!!!!!!!!!!!xx            !   o o                  ",
             "                                                               xxxx!!!!!xxxx             !                        ",
             "                                               x     x            xxxxxxx        xxx     !   xxx                  ",
             "                                               x     x                           x x     !   x x                  ",
             "                                               x     x                             x     !  xx                    ",
             "                                               x     x                             xx    !   x                    ",
             "                                               xx    x                             x     !   x                    ",
             "                                               x     x               x   x         x     !   x                    ",
             "               xxxxxxx        xxx   xxx        x     x               x   x         x     !  xx                    ",
             "              xxxxxxxxx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx   !   x                    ",
             "             xxxxxxxxxxx        x   x          x    xx               x   x   x           !   x                    ",
             "     @       xxxxxxxxxxx        x   x          x     x               x   x   x           !   x                    ",
             "    xxx      xxxxxxxxxxx        x   xx         x     x               x   xxxxx   xxxxxx  !  xx                    ",
             "    x x      xxxxxxxxxxx       xx   xx         x     x               x           x x     v   x                    ",
             "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
             "!!!!x x!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx   o    x                    ",
             "!!!!x x!!!!!!xxxxxxxxxxx!!!!!x    o                 xx!!!!!!xx !                    xxxx    xx                    ",
             "!!!!x x!!!!!!xxxxxxxxxxx!!!!!x                     xx!!!!!!xx  !                     xxxxxxxx                     ",
             "!!!!x x!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
             "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
             "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  },          




  {
  name: 'Sahara',
  difficulty: 5,
  coins: 18,
  powerups: ['haste', 'lowjump', 'doublejump'],
  layout:   ["                                                                                                              ",
             "                                                                                                              ",
             "                                                                                                              ",
             "                                                                                                              ",
             "                                                                                                              ",
             "                                        o                                                                     ",
             "                                                                                                              ",
             "                                        x                                                                     ",
             "                                        x                                                                     ",
             "                                        x                                                                     ",
             "                                        x                                                                     ",
             "                                       xxx                                  o                                 ",
             "                                       x x                 !!!        !!!  xxx                                ",
             "                                       x x                 !x!        !x!                                     ",
             "                                     xxx xxx                x          x                                      ",
             "                                      x   x                 x   oooo   x       xxx                            ",
             "                                      x   x                 x          x      x!!!x                           ",
             "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
             "                                     xx   xx      x   x      x                                                ",
             "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
             "                                      x   x           x                    x!!!x                              ",
             "                                      x   x           x                     xxx                               ",
             "                                     xx   xx          x                                                       ",
             "                                      x   x= = = =    x            xxx                                        ",
             "                                      x   x           x           x!!!x                                       ",
             "                                      x   x    = = = =x     o      xxx       xxx                              ",
             "                                     xx   xx          x                     x!!!x                             ",
             "                              o       x   x           x     x                xxv        xxx                   ",
             "                                      x   x           x              x                 x!!!x                  ",
             "                             xxx xxx xxx xxx     o    x!!!!!!!!!!!!!!x                   vx                   ",
             "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
             "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
             "                             xx           xx                                         xxx                      ",
             "  xxx                         x     x     x                                         x!!!x                xxx  ",
             "  x x                         x    xxx    x                                          xxx                 x x  ",
             "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
             "  x                           x           x                              x   x                             x  ",
             "  x                           xx          x                              x x x                             x  ",
             "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
             "  x                xxx             o     x                              x         xxx                      x  ",
             "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
             "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
             "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
             "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
             "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
             "                                                                                                              ",
             "                                                                                                              "],
  },          






  {
  name: 'Shasta',
  rating: 8,
  coins: 18,
  powerups: ['haste', 'lowjump', 'doublejump'],
  layout:   ["                                                                                                  xxx x       ",
             "                                                                                                      x       ",
             "                                                                                                  xxxxx       ",
             "                                                                                                  x           ",
             "                                                                                                  x xxx       ",
             "                          o                                                                       x x x       ",
             "                                                                                             o o oxxx x       ",
             "                   xxx                                                                                x       ",
             "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
             "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
             "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
             "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
             "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
             "                                                                                                              ",
             "          o              xxx                              xx                                                  ",
             "                                                                                                              ",
             "                                                                                                              ",
             "                                                      xx                                                      ",
             "                   xxx         xxx                                                                            ",
             "                                                                                                              ",
             "                          o                                                     x      x                      ",
             "                                                          xx     xx                                           ",
             "             xxx         xxx         xxx                                 x                  x                 ",
             "                                                                                                              ",
             "                                                                 ||                                           ",
             "  xxxxxxxxxxx                                                                                                 ",
             "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
             "  x         x   x       x   x       x   x                 ||                  x     x                         ",
             "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
             "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
             "        x=                  =                =x   x                     xxx                                   ",
             "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
             "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
             "                                                                                                              "]
  }
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
